name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set docker tag
      run: |
        echo "DOCKER_TAG=$(date +%s)" >> ${GITHUB_ENV}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ripost-floating:${{ env.DOCKER_TAG }} 
    - name: Test
      run: |
        mkdir -p results/
        docker run --rm ripost-floating:${{ env.DOCKER_TAG }} > results/results-${{ env.DOCKER_TAG }}.csv
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add results/results-${{ env.DOCKER_TAG }}.csv
        git commit -am "${{ env.DOCKER_TAG }}: Add new results"
        git push
        
